1. Преобразование типов - это преобразование объекта из одного типа данных в другой тип данных.
2. Неявное преобразование типов автоматически выполняется интерпретатором Python.
3. Python позволяет избежать потери данных при неявном преобразовании типов.
4. Явное преобразование типов также называется приведением типов, типы данных объектов преобразуются пользователем с использованием предопределенных функций.
5. При приведении типов может произойти потеря данных, поскольку мы приводим объект к определенному типу данных.

![[try_except_else.703aaeeb63d3.avif]]

## Создание пользовательского исключения
```python
class PlatformException(Exception):
    """Incompatible platform."""

def linux_interaction():
    if "linux" not in sys.platform:
        raise PlatformException("Function can only run on Linux systems.")
    print("Doing Linux things.")
```
# Список исключений

| Исключение            | Описание                                                                                            |
| --------------------- | --------------------------------------------------------------------------------------------------- |
| ArithmeticError       | Вызывается при возникновении ошибки в числовых вычислениях                                          |
| AssertionError        | Возникает при сбое инструкции assert                                                                |
| AttributeError        | Вызывается при сбое ссылки на атрибут или его назначения                                            |
| Exception             | Базовый класс для всех исключений                                                                   |
| EOFError              | Возникает, когда метод input() выполняет условие "конец файла" (EOF)                                |
| FloatingPointError    | Возникает при сбое вычисления с плавающей запятой                                                   |
| GeneratorExit         | Возникает при закрытии генератора (с помощью метода close())                                        |
| ImportError           | Вызывается, когда импортированный модуль не существует                                              |
| IndentationError      | Возникает, когда неверен отступ                                                                     |
| IndexError            | Возникает, когда индекс последовательности не существует                                            |
| KeyError              | Возникает, когда ключ не существует в словаре                                                       |
| KeyboardInterrupt     | Вызывается, когда пользователь нажимает Ctrl + c, Ctrl + z или Delete                               |
| LookupError           | Вызывается, когда не удается найти возникшие ошибки                                                 |
| MemoryError           | Возникает, когда программе не хватает памяти                                                        |
| NameError             | Вызывается, когда переменная не существует                                                          |
| NotImplementedError   | Возникает, когда абстрактному методу требуется, чтобы унаследованный класс переопределил этот метод |
| OSError               | Возникает, когда операция, связанная с системой, вызывает ошибку                                    |
| OverflowError         | Возникает, когда результат числового вычисления слишком велик                                       |
| ReferenceError        | Возникает, когда слабый ссылочный объект не существует                                              |
| RuntimeError          | Вызывается при возникновении ошибки, которая не относится к каким-либо конкретным исключениям       |
| StopIteration         | Возникает, когда метод next() итератора больше не имеет значений                                    |
| SyntaxError           | Вызывается при возникновении синтаксической ошибки                                                  |
| TabError              | Возникает, когда отступ состоит из табуляций или пробелов                                           |
| SystemError           | Вызывается при возникновении системной ошибки                                                       |
| SystemExit            | Возникает при вызове функции sys.exit()                                                             |
| TypeError             | Возникает при объединении двух разных типов                                                         |
| UnboundLocalError     | Возникает, когда перед назначением делается ссылка на локальную переменную                          |
| UnicodeError          | Возникает при возникновении проблемы с unicode                                                      |
| UnicodeEncodeError    | Возникает при возникновении проблемы с кодировкой Unicode                                           |
| UnicodeDecodeError    | Возникает при возникновении проблемы с декодированием Unicode                                       |
| UnicodeTranslateError | Возникает при возникновении проблемы с переводом в юникод                                           |
| ValueError            | Возникает, когда в указанном типе данных задано неправильное значение                               |
| ZeroDivisionError     | Возникает, когда второй оператор в делении равен нулю                                               |
